---
- import_playbook: ../playbooks/cluster-boostrap/prerequisites.yml
- import_playbook: ../playbooks/cluster-boostrap/setting_up_nodes.yml
- import_playbook: ../playbooks/cluster-boostrap/configure_master_node.yml
- import_playbook: ../playbooks/cluster-boostrap/configure_worker_nodes.yml
